name: 'Run Playwright tests'
description: 'Run Playwright tests and upload the report'
inputs:
  before:
    required: false
  after:
    required: false
  skip:
    required: false
  npm-prefix:
    required: false
    default: "."
runs:
  using: "composite"
  steps:

      - name: setup dir for screenshots
        id: setup-image-dir
        shell: sh
        run: |
          set -eu
          TIMESTAMP=$(date '+%Y%m%d%H%M%S')
          sed -i -E "/\['html', \{[^}]+\}\]/s/\{([^}]+)\}/{\1, attachmentsBaseURL: 'assets\/images\/$TIMESTAMP\/'}/" playwright.config.ts
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_OUTPUT

      - name: before ${{ inputs.test-name }}
        if: ${{ inputs.before && !inputs.skip }}
        shell: sh
        run: |
          ${{ inputs.before }}

      - name: run ${{ inputs.test-name }}
        if: ${{ !inputs.skip }}
        shell: sh
        run: |
          npm run pw-tests
        env:
          HOME: /root

      - name: after ${{ inputs.test-name }}
        if: ${{ inputs.after && !inputs.skip }}
        shell: sh
        run: |
          ${{ inputs.after }}

      - name: publish report ${{ inputs.test-name }}
        id: publish-report
        if:  ${{ !inputs.skip && always() }}
        shell: sh
        run: |
          set -eu
          TIMESTAMP=${{ steps.setup-image-dir.outputs.TIMESTAMP }}
          PAGE_DIR=app/views/pages
          IMAGE_DIR=app/assets/images/$TIMESTAMP

          cd ./playwright-report
          if [ -d "./data" ]; then
              mkdir -p $IMAGE_DIR
              mv ./data/* $IMAGE_DIR
          fi
          mkdir -p $PAGE_DIR
          mv ./index.html $PAGE_DIR/$TIMESTAMP.liquid

          MPKIT_URL=$UPLOAD_HOST
          pos-cli deploy -p

          URL=$MPKIT_URL/$TIMESTAMP
          echo "REPORT_URL=$URL" >> $GITHUB_OUTPUT
          echo "pw-tests-report-url=$URL" >> $GITHUB_OUTPUT

      - name: remove report directory
        if:  ${{ !inputs.skip && always() }}
        shell: sh
        run: |
          rm -rf playwright-report

      - name: summary
        if:  ${{ !inputs.skip && always() }}
        shell: sh
        run: |
          echo "### TEST REPORT" >> $GITHUB_STEP_SUMMARY
          echo "#### Status: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "#### Test report URL: ${{ steps.publish-report.outputs.REPORT_URL }}" >> $GITHUB_STEP_SUMMARY

      - name: skip ${{ inputs.test-name }}
        if: ${{ !!inputs.skip }}
        shell: sh
        run: echo skipping ${{ inputs.test-name }}

